//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDLite.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EDDLite.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Concept by:
        ///Cmdr Robby
        ///
        ///Developers for this release series:
        ///Robby (Releaser)
        ///
        ///Underlying codebase from the EDDiscovery Team
        ///.
        /// </summary>
        internal static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EDCD {
            get {
                object obj = ResourceManager.GetObject("EDCD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff0\deff0\stshfdbch0\stshfloch31506\stshfhich31506\stshfbi31506\deflang2057\deflangfe2057\themelang2057\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f34\fbidi \froman\fcharset0\fprq2{\*\panose 02040503050406030204}Cambria Math;}
        ///{\f37\fbidi \fswiss\fcharset0\fprq2{\*\panose 020f0502020204030204}Calibri;}{\flomajor\f31500\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EDD_License {
            get {
                return ResourceManager.GetString("EDD_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EDDB {
            get {
                object obj = ResourceManager.GetObject("EDDB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon edlogo_3mo_icon {
            get {
                object obj = ResourceManager.GetObject("edlogo_3mo_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EDShipYard {
            get {
                object obj = ResourceManager.GetObject("EDShipYard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EDSM {
            get {
                object obj = ResourceManager.GetObject("EDSM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Inara {
            get {
                object obj = ResourceManager.GetObject("Inara", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShowOnCoriolis {
            get {
                object obj = ResourceManager.GetObject("ShowOnCoriolis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spansh {
            get {
                object obj = ResourceManager.GetObject("spansh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://coriolis.io/import?.
        /// </summary>
        internal static string URLCoriolis {
            get {
                return ResourceManager.GetString("URLCoriolis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://edcd.github.io/.
        /// </summary>
        internal static string URLEDCD {
            get {
                return ResourceManager.GetString("URLEDCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://eddb.io/.
        /// </summary>
        internal static string URLeddb {
            get {
                return ResourceManager.GetString("URLeddb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://eddb.io/station/market-id/.
        /// </summary>
        internal static string URLEDDBStationMarketId {
            get {
                return ResourceManager.GetString("URLEDDBStationMarketId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://eddb.io/system/name/.
        /// </summary>
        internal static string URLEDDBSystemName {
            get {
                return ResourceManager.GetString("URLEDDBSystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.elitedangerous.com/.
        /// </summary>
        internal static string URLEDHomepage {
            get {
                return ResourceManager.GetString("URLEDHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.edshipyard.com/.
        /// </summary>
        internal static string URLEDShipyard {
            get {
                return ResourceManager.GetString("URLEDShipyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.edsm.net/.
        /// </summary>
        internal static string URLedsm {
            get {
                return ResourceManager.GetString("URLedsm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.github.com/repos/EDDiscovery/EDDLite/.
        /// </summary>
        internal static string URLGithubDownload {
            get {
                return ResourceManager.GetString("URLGithubDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://inara.cz/galaxy-starsystem/?search=.
        /// </summary>
        internal static string URLInaraStarSystem {
            get {
                return ResourceManager.GetString("URLInaraStarSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://inara.cz/galaxy-station/?search=.
        /// </summary>
        internal static string URLInaraStation {
            get {
                return ResourceManager.GetString("URLInaraStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://discordapp.com/invite/0qIqfCQbziTWzsQu.
        /// </summary>
        internal static string URLProjectDiscord {
            get {
                return ResourceManager.GetString("URLProjectDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string URLProjectEDForumPost {
            get {
                return ResourceManager.GetString("URLProjectEDForumPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/EDDiscovery/EDDLite/issues.
        /// </summary>
        internal static string URLProjectFeedback {
            get {
                return ResourceManager.GetString("URLProjectFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/EDDiscovery/EDDLite.
        /// </summary>
        internal static string URLProjectGithub {
            get {
                return ResourceManager.GetString("URLProjectGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/EDDiscovery/EDDLite/blob/master/LICENSE.
        /// </summary>
        internal static string URLProjectLicense {
            get {
                return ResourceManager.GetString("URLProjectLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/EDDiscovery/EDDLite/releases.
        /// </summary>
        internal static string URLProjectReleases {
            get {
                return ResourceManager.GetString("URLProjectReleases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/EDDiscovery/EDDLite/wiki.
        /// </summary>
        internal static string URLProjectWiki {
            get {
                return ResourceManager.GetString("URLProjectWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://spansh.co.uk/body/.
        /// </summary>
        internal static string URLSpanshBodyId {
            get {
                return ResourceManager.GetString("URLSpanshBodyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://spansh.co.uk/station/.
        /// </summary>
        internal static string URLSpanshStationMarketId {
            get {
                return ResourceManager.GetString("URLSpanshStationMarketId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://spansh.co.uk/system/.
        /// </summary>
        internal static string URLSpanshSystemSystemId {
            get {
                return ResourceManager.GetString("URLSpanshSystemSystemId", resourceCulture);
            }
        }
    }
}
